@startuml
'https://plantuml.com/class-diagram

class Carta{
    - int numero;
    - String palo;

    + void toString();
}

class Baraja{
    - List<Carta> cartas;

    + void barajar()
    + void siguienteCarta()
    + int cartasDisponibles()
    + void darCartas()
    + void cartasMonton()
    + void mostrarBaraja()
}

Baraja *--"1.*" Carta
@enduml